# SITE SETUP

custom_css:
   - css/custom.css

style:
  primary: "#C5A253"  # Forbes Gold
  link: "#C5A253"
  background: "#FFFFFF"
  home_section_odd: "#FFFFFF"
  home_section_even: "#F5F5F5"

appearance:
  mode: system
  color: neutral

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Dongkun Lee'
    description: 'Dongkun Lee's research on Generative AI, XR, and Multimodal Systems.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: false
    logo:
      text: "Dongkun Lee"

footer:
  copyright:
    notice: '© {year} Dongkun Lee. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

features:
  math:
    enable: false
  privacy_pack:
    enable: false